name: Test Package

# all branches except master
# https://stackoverflow.com/questions/57699839/github-actions-how-to-target-all-branches-except-master
on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 13
      - run: yarn
      - run: yarn build
      - run: yarn test
